---
- name: create rancher configuration directory
  file:
    path: /etc/rancher/k3s/
    state: directory

- name: create registry configuration
  copy:
    dest: "/etc/rancher/k3s/registries.yaml"
    content: |
      mirrors:
        "192.168.0.200:5000":
          endpoint:
            - "http://192.168.0.200:5000"

- name: copy k3s service file
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s-node.service"
    owner: root
    group: root
    mode: 0755

- name: enable and check k3s service
  systemd:
    name: k3s-node
    daemon_reload: yes
    state: restarted
    enabled: yes
